// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.4.8_@babel+plugin-pr_12e180c290d6d55b6bf74d5eb4b7d41c/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.4.8_@babel+plugin-pr_12e180c290d6d55b6bf74d5eb4b7d41c/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.4.8_@babel+plugin-pr_12e180c290d6d55b6bf74d5eb4b7d41c/node_modules/nuxt/dist/app/plugins/router.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.4.8_@babel+plugin-pr_12e180c290d6d55b6bf74d5eb4b7d41c/node_modules/nuxt/dist/app/plugins/payload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.4.8_@babel+plugin-pr_12e180c290d6d55b6bf74d5eb4b7d41c/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.4.8_@babel+plugin-pr_12e180c290d6d55b6bf74d5eb4b7d41c/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.4.8_@babel+plugin-pr_12e180c290d6d55b6bf74d5eb4b7d41c/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.4.8_@babel+plugin-pr_12e180c290d6d55b6bf74d5eb4b7d41c/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+color-mode@4.0.1_magicast@0.5.3/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+color-mode@4.0.1_magicast@0.5.3/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+icon@2.2.3_magicast@0_074244cffed2ee9eb2f46ecf015ccced/node_modules/@nuxt/icon/dist/runtime/plugin.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+ui@4.9.0_0c61aa8d0aac9c35d87536818b7d7dd4/node_modules/@nuxt/ui/dist/runtime/plugins/colors.js")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt:payload' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | '@nuxt/icon' | 'nuxt:global-components'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
